version: '3.8'

services:
  data-input:
    build: ./data-input
    image: data-input
    container_name: data-input
    ports:
      - "8080:8080"
    depends_on:
      buildings-audit-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://buildings-audit-db:5432/buildings-audit
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  buildings-audit-db:
    image: postgres:16.1
    container_name: buildings-audit-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: buildings-audit
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

volumes:
  postgres_data: