CREATE TABLE IF NOT EXISTS engineers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    jobTitle VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    CONSTRAINT pk_engineers PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(100) NOT NULL,
    house VARCHAR(100) NOT NULL,
    apartment VARCHAR(100) NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS buildings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address_id BIGINT NOT NULL,
    CONSTRAINT pk_buildings PRIMARY KEY (id),
    CONSTRAINT fk_buildings_address_id FOREIGN KEY (address_id) REFERENCES address(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS measurement_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) UNIQUE NOT NULL,
    CONSTRAINT pk_measurement_type PRIMARY KEY (id),
);

CREATE TABLE IF NOT EXISTS unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) UNIQUE NOT NULL,
    CONSTRAINT pk_unit PRIMARY KEY (id),
);

CREATE TABLE IF NOT EXISTS measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    measurement_date TIMESTAMP DEFAULT NOW(),
    parameter_string_value VARCHAR(100) NOT NULL,
    parameter_double_value NUMERIC(9,6) NOT NULL,
    comments TEXT NOT NULL,
    measurement_type_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    engineer_id BIGINT NOT NULL,
    building_id BIGINT NOT NULL,
    CONSTRAINT pk_measurements PRIMARY KEY (id),
    CONSTRAINT fk_measurements_measurement_type_id FOREIGN KEY (measurement_type_id) REFERENCES measurement_type(id) ON DELETE RESTRICT,
    CONSTRAINT fk_measurements_unit_id FOREIGN KEY (unit_id) REFERENCES unit(id) ON DELETE RESTRICT,
    CONSTRAINT fk_measurements_engineer_id FOREIGN KEY (engineer_id) REFERENCES engineers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_measurements_building_id FOREIGN KEY (building_id) REFERENCES buildings(id) ON DELETE RESTRICT
);