CREATE TABLE IF NOT EXISTS engineers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstName VARCHAR(251) NOT NULL,
    lastName VARCHAR(251) NOT NULL,
    jobTitle VARCHAR(251) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    CONSTRAINT pk_engineers PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS buildings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address VARCHAR(251) NOT NULL,
    buildingType VARCHAR(251) NOT NULL,
    CONSTRAINT pk_buildings PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    measurement_date TIMESTAMP DEFAULT NOW(),
    measurement_type VARCHAR(100) NOT NULL,
    parameter_name VARCHAR(100) NOT NULL,
    parameter_value NUMERIC(9,6) NOT NULL,
    unit VARCHAR(20) NOT NULL CHECK (state IN ('CM', 'MM', 'M')),
    comments TEXT NOT NULL,
    engineer_id BIGINT NOT NULL,
    building_id BIGINT NOT NULL,
    CONSTRAINT pk_measurements PRIMARY KEY (id),
    CONSTRAINT fk_measurements_engineer_id FOREIGN KEY (engineer_id) REFERENCES engineers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_measurements_building_id FOREIGN KEY (building_id) REFERENCES buildings(id) ON DELETE RESTRICT
);